### ISSUE TITLE
NX8048K050_011R not working from V4.1.4 and above

### ISSUE THREAD

**Issue by ffl-la** [MMMZZZZ/Syntherrupter#25]
NX8048K050_011R stopped working from firmware version 4.1.4 and the above. Last known good Version is 4.1.3

Lg Alessio

**Comment by MMMZZZZ** [comment]
Hi @ffl-la, 

I don't own a NX8048K050 display, so I only have the Nextion debugger to check the binaries. With the corresponding editor version (1.62.1), the TFT file opens and runs fine. 

As the [release notes](https://github.com/MMMZZZZ/Syntherrupter/releases/tag/v4.1.4) say, the upgraded Nextion bootloader is much more sensitive to power supply issues. If changing the power supply, changing/shortening the supply cables and adding additional capacitance to the display don't fix the issue, you should measure the 5V and the 3.3V rail directly on the Nextion PCB to verify that they don't have any drops. Especially the 3.3V must be absolutely stable. For reference, when I encountered this issue, I made a [detailed post](https://unofficialnextion.com/t/new-nextion-editor-1-62-1-is-available/1182/9) about it. If you're still unsure, just post a picture of the traces here. 

If this doesn't fix your issues, it'd be very helpful to get some more details about how exactly the device fails. 

Kind regards,
Max

**Comment by ffl-la** [comment]
Hallo Max

Vielen Dank! Ich hatte den verdacht es liegt an der Versorgung, ich habe es
mal mit einer Powerbank versucht hat aber auch nicht funktioniert. Wenn ich
Zeit hab werde ich mal messen.

Lg
Alessio

Am Di., 1. Juni 2021 um 23:57 Uhr schrieb MMMZZZZ ***@***.***

**Comment by MMMZZZZ** [comment]
*Closed because of inactivity*
