### ISSUE TITLE
Startup fails when using Nextion Editor/Simulator

### ISSUE THREAD

**Issue by MMMZZZZ** [MMMZZZZ/Syntherrupter#34]
Im having problems with tiva firmware compatibility and nextion editor on version `4.2.0` and higher using nextion editor version `1.63.3`. The nextion editor remains black even after resetting microcontroller. Versions `4.1.4` and earlier work with nextion editor version `1.16.3`.

_Originally posted by @WayneSeng in https://github.com/MMMZZZZ/Syntherrupter/issues/7#issuecomment-974708332_

**Comment by MMMZZZZ** [comment]
@WayneSeng: Thank you for the bug report. I moved your report to a new issue since it has nothing to do with the one you commented on. 

I've fixed the issue you described and released a new version (v4.2.1). 

Kind regards,
Max

**Comment by PoleTransformer** [comment]
@MMMZZZZ Thanks can confirm issue is fixed!
